apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: {{NAMESPACE}}
spec:
  hard:
    requests.cpu: "1000"
    requests.memory: 4000Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max
  namespace: {{NAMESPACE}}
spec:
  limits:
  - min:
      cpu: "100m"
    defaultRequest:
      cpu: "100m"
    type: Container